feature: resolve private maven repo with GPG by leiningen
liquidz/antq pull request #237
Opened 2023-09-16 07:49 UTC by blue0513

Thank you for the amazing library 🎉 
I have a suggestion bellow.

## What

- Allow antq to read `~/.lein/profiles.clj`
- Allow antq to decrypt `credentials.clj.gpg`

## Why

- antq cannot resolve private maven repos listed in `profiles.clj`
- antq cannot decrypt `credentials.clj.gpg` to fetch artifact versions via leiningen

### Reploduction steps

1. Create the following Clojure code and save it as `/path/to/my-project/project.clj`:

```clojure
(defproject dep-test "0.0.1-SNAPSHOT"
  :dependencies [[my/provate-lib "0.0.1"]]) ;; latest is `0.0.2`
```

2. Create the following Clojure code and save it as `~/.lein/profiles.clj`:
```clojure
;; Using GPG. ref: https://cljdoc.org/d/leiningen/leiningen/2.9.3/doc/using-gpg
{:user {:repositories [["internal-snapshots" {:url "https://my/private/repository"
                                              :creds :gpg}]]}}
```

3. Execute the following command:
```shell
$ clojure -M:outdated --directory="/path/to/my-project"
```

The output should be as follows:
```shell
| :file                           | :name              | :current | :latest         |
|---------------------------------+--------------------+----------+-----------------|
| /path/to/my-project/project.clj | my/private-lib     | 0.0.1    | Failed to fetch |
```

2023-09-18 21:07 UTC, liquidz commented
@blue0513 Sorry for late reply 🙇 
I'll have a look later.

2023-09-19 09:04 UTC, liquidz requested changes
@blue0513 Thanks for your contribution!

2023-09-20 15:47 UTC, blue0513 commented on src/antq/util/leiningen.clj
> +        (if (.exists cred-file)
Ah... and I apologize for forgetting to mention the MOST important point.

These changes in this file heavily reference Leiningen's code.
Leiningen is under the EPL license, so we should take Copyleft into consideration.

But, I believe Antq is already under the EPL license.
So do we not need to take any special precautions?

2023-09-23 06:13 UTC, blue0513 commented on src/antq/util/maven.clj
> +  (let [{:keys [username password]} (->> (u.lein/read-credential) vals first)]
Yes, that's correct

2023-09-23 06:14 UTC, blue0513 commented
@liquidz Thx for your review. I've responded to your review ! 
[`0f02594` (#237)](https://github.com/liquidz/antq/pull/237/commits/0f02594ab4f85f8dd5e578363395498a0f531a98)

2023-09-23 06:19 UTC, blue0513 commented on src/antq/util/leiningen.clj
> +        (if (.exists cred-file)
However, I believe this implementation is quite common, so there is no need to be overly concerned about it.

2023-09-28 21:04 UTC, liquidz requested changes
@blue0513 I'm sorry for the delayed response once again.
It was hard to find the time to test with the authenticated mvn repository, which has caused the delay.

2023-09-28 21:04 UTC, liquidz commented on src/antq/util/leiningen.clj
> +                 (filter (fn [[pattern, _]] (re-matches pattern url)))
> [pattern, _]

BTW, extra comma is not needed.

2023-10-01 08:00 UTC, blue0513 commented on src/antq/util/leiningen.clj
> +        (if (.exists cred-file)
Yes, I agree 👍

2023-10-01 08:01 UTC, blue0513 commented
@liquidz Big thx! I treated your review by this commit: 
 [`25bb320` (#237)](https://github.com/liquidz/antq/pull/237/commits/25bb3200d186418eec74ef7ba734f8c943115d06)

2023-10-02 20:47 UTC, liquidz approved these changes
@blue0513 Thanks for your fixes! LGTM

2023-10-02 20:47 UTC, merged

2023-10-02 21:24 UTC, liquidz commented
@blue0513 Just released v2.7.1133 :)

2023-10-04 13:57 UTC, blue0513 commented
@liquidz  Thank you for your kind review & Great library !!!