Add forced focus option
liquidz/antq pull request #262
Opened 2024-09-17 12:25 UTC by Kaspazza

Hi, it's me again.

We've been using previously programmatic API, but due to compatibility issues with Babashka, we've moved to CLI. 
Currently, there is no option in CLI to force a specific version of the dependency to update.

Our use-case to be more specific, is that we want to update to the not-existing yet version as we are deploying multiple co-dependent apps together. Which was possible in API by just supplying deps we want it to update.

The focus option seemed best to me for that use case, as we want to focus on that dependency and update it to a specific version.
In terms of syntax, exclude follows a similar syntax of being able to exclude dep completely or specific version, currently focus was not leveraging the version option, so I've added this behavior under that versioning syntax.

The feature was done in a manner that it should not break any existing behaviors, so I estimate the change impact as minor non-breaking since all the previous usage of focus and other features is unchanged both on the caller side and in the code itself.

2024-09-18 22:34 UTC, liquidz commented
@Kaspazza Thanks for your contribution!

> The CLI focus option seems best for me for that feature, as we want to focus on that dependency and update it to a specific version.

Make sence! I'll have a look :)

2024-09-20 23:12 UTC, liquidz requested changes

2024-09-20 23:12 UTC, liquidz commented on src/antq/core.clj
> +    (:latest-version matching-artifact)))
When using the result of `forced-artifact-version-map`, you can simply use `(get % (:name dep))`.

2024-09-20 23:12 UTC, liquidz commented on src/antq/core.clj
> +      (assoc dep :latest-version latest-version))))
We are replacing the version number here, but by this point, the retrieval of the actual version number information has already been fetched from maven, github, etc.

If a version number is specified with focus, wouldn't we want to skip retrieving the version number information? (It takes time, and finally, it's not used anyway.)

2024-09-20 23:12 UTC, liquidz commented on src/antq/core.clj
> +  [dep options forced-artifacts]
It's hard to read because you're shadowing the function name, so could you use a name different from the function name?

2024-09-22 14:08 UTC, Kaspazza commented on src/antq/core.clj
> +    (if (some? (second specific-version)) (first specific-version) artifact)))
Okay, done!

2024-09-22 14:59 UTC, Kaspazza commented
Thanks for the review, I've applied your suggestions.
WDYT?

2024-09-25 21:54 UTC, liquidz commented
@Kaspazza Thanks! I'll have a look this weekend :)

2024-09-27 21:16 UTC, liquidz requested changes
@Kaspazza Overall, looks good!
Could you fix few minor revisions at the end?

2024-09-27 21:16 UTC, liquidz commented on src/antq/core.clj
> +    (assoc dep :forced-ver forced-ver)
Could you  change the keyword to `:forced-version` without abbreviating?

2024-09-27 21:16 UTC, liquidz commented on src/antq/core.clj
> +        uniq-deps-with-vers (doall (pmap #(assoc-versions %  options) uniq-deps))
Please remove extra space.

2024-09-28 11:43 UTC, Kaspazza commented
@liquidz Done

2024-09-29 00:12 UTC, liquidz approved these changes
@Kaspazza Thank you so much!

2024-09-29 00:12 UTC, merged

2024-09-29 00:25 UTC, liquidz commented
@Kaspazza Just released [v2.10.1241](https://github.com/liquidz/antq/releases/tag/2.10.1241) :)