Add circleci support
liquidz/antq pull request #265
Opened 2024-10-31 10:01 UTC by nenadalm

2024-11-03 23:22 UTC, liquidz requested changes
@nenadalm Thanks for your contribution!
This is awesome work!

There are a few points I’d like you to revise, so could you check them?

2024-11-03 23:22 UTC, liquidz commented on src/antq/ver/circle_ci_orb.clj
> +      slurp
Please add error handlings.
e.g. https://github.com/liquidz/antq/blob/79f42b50f99fa247fddfe8fd89cdc494b1b96dce/src/antq/ver/github_tag.clj#L59-L67

2024-11-03 23:22 UTC, liquidz commented on src/antq/ver/circle_ci_orb.clj
> +      slurp
Please add error handlings here too.

2024-11-04 09:57 UTC, nenadalm commented
Thanks. All remarks should be fixed now.

2024-11-06 21:44 UTC, liquidz approved these changes
@nenadalm LGTM :) Thanks!

2024-11-06 21:44 UTC, merged

2024-11-06 22:01 UTC, liquidz commented
@nenadalm Just released v2.11.1250 :)