Offer a Leiningen plugin
liquidz/antq pull request #80
Opened 2021-05-31 12:17 UTC by vemv

First cut, let me know what you think!

I verified that it works locally:

![image](https://user-images.githubusercontent.com/1162994/120191199-ee205780-c219-11eb-936b-568b33f72e48.png)

(Clojure "1.11.99" is, of course, just a local hack)

2021-05-31 21:33 UTC, liquidz requested changes
@vemv Thanks! Overall the PR looks good and it works great!

Could you update CHANGELOG.adoc too?

2021-05-31 21:33 UTC, liquidz commented on src/antq/dep/leiningen.clj
> +                            :version      version
I'm not using alignment in this code base.
```suggestion
        (r/map->Dependency {:project :leiningen
                            :type :java
                            :file file-path
                            :name (normalize-name dep-name)
                            :version version
```

2021-05-31 21:33 UTC, liquidz commented on src/leiningen/antq.clj
> +                                                    :repositories repos}))))
Same here.
```suggestion
                                (r/map->Dependency {:project :leiningen
                                                    :type :java
                                                    :file "project.clj"
                                                    :name (dep.lein/normalize-name dep-name)
                                                    :version version
                                                    :repositories repos}))))
```

2021-06-01 23:05 UTC, vemv commented
Thanks for the review! Ready again. Build is green in https://github.com/reducecombine/antq/actions

2021-06-02 20:45 UTC, liquidz approved these changes
@vemv Thanks! LGTM

2021-06-02 20:45 UTC, merged

2021-06-02 21:24 UTC, vemv commented
Cheers 🙌

I was thinking of adding an end-to-end test for the Lein plugin. Sounds good?

The way I did it for another lein plugin was with a bash script. This way it's natural to express various steps e.g. `lein install`, then running the plugin and expecting non-zero, then running the plugin and expecting zero, etc.

Example: https://github.com/rm-hull/lein-nvd/blob/ed8780007256a3c41dfad144ababbd4b05727995/.github/integration_test.sh

2021-06-02 22:54 UTC, liquidz commented
@vemv Awesome! It's good to add tests!

2021-06-03 08:18 UTC, vemv commented
Thanks for the confirmation! Will do